name: GitHub Actions
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v2

      - uses: bahmutov/npm-install@v1
        with:
          working-directory: sol

      - name: Hardhat tests
        run: npm test
        working-directory: sol